name: trainertimerpro
description: progress project on trainer timer

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  circular_countdown: ^2.1.0
  flutter:
    sdk: flutter
  gap: ^2.0.0
  timer_controller: ^0.1.0

  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  intl: ^0.17.0

  cupertino_icons: ^1.0.3

  audioplayers: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/mp3/basrutten/getreadyin5.mp3
    - assets/mp3/basrutten/round1.mp3
    - assets/mp3/basrutten/four.mp3
    - assets/mp3/basrutten/jab.mp3
    - assets/mp3/basrutten/rightstraightlefthook.mp3
    - assets/mp3/basrutten/rightstraightlefthookrightstraight.mp3
    - assets/mp3/basrutten/lefthookrightuppercut.mp3
    - assets/mp3/basrutten/lefthookrightuppercutlefthook.mp3
    - assets/mp3/basrutten/threeandalefthook.mp3
    - assets/mp3/basrutten/threeandalefthookrightstraight.mp3
    - assets/mp3/basrutten/twoandarightstraight.mp3
    - assets/mp3/basrutten/fourandarightstraight.mp3
    - assets/mp3/basrutten/threehooks.mp3
    - assets/mp3/basrutten/twoandathree.mp3
    - assets/mp3/basrutten/onetwo.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
